name: Build JDWP Toolkit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_debug:
    name: "Build Release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        name: Checkout libjdwp
        with:
          repository: '${{ github.repository_owner }}/libjdwp'
          path: '${{ github.workspace }}/libjdwp'
      - name: Install build dependencies
        run: sudo apt update && sudo apt install -y libglx-dev libgl1-mesa-dev qt6-base-dev
      - name: Build libjdwp
        run: cd libjdwp && cmake -B build -DCMAKE-BUILD_TYPE=Release && cmake --build build --target jdwp && cd ..
      - name: Configure JDWP Toolkit
        run: cmake -B build -DCMAKE_CXX_FLAGS="-I${{ github.workspace }}/libjdwp/include -L${{ github.workspace }}/libjdwp/build"
      - name: Build library
        run: cmake --build build

