name: Build JDWP Toolkit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_debug:
    name: "Build Debug"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        name: Checkout libjdwp
        with:
          repository: '${{ github.repository_owner }}/libjdwp'
          path: '${{ github.workspace }}/libjdwp'
      - name: Install build dependencies
        run: sudo apt update && sudo apt install -y qt6-base-dev
      - name: Build libjdwp
        run: cd libjdwp && cmake -B build -DCMAKE-BUILD_TYPE=Release && cmake --build build --target jdwp && cd ..
      - name: Configure JDWP Toolkit
        run: cmake -B build -DCMAKE_CXX_FLAGS="-I./libjdwp/include -L./libjdwp/build"
      - name: Build library
        run: cmake --build build

  test_unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build_debug
    steps:
      - uses: actions/checkout@v4
      - name: Install test and runtime dependencies
        run: sudo apt update --quiet && sudo apt install --quiet -y libcmocka-dev
      - name: Configure unit tests
        run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DJDWP_UNIT_TEST=1
      - name: Build unit tests
        run: cmake --build build
      - name: Run unit tests
        run: ctest --test-dir build --verbose

  test_unit_memcheck:
    name: Unit Tests (with memcheck)
    runs-on: ubuntu-latest
    needs: build_debug
    steps:
      - uses: actions/checkout@v4
      - name: Install test and runtime dependencies
        run: sudo apt update --quiet && sudo apt install --quiet -y libcmocka-dev valgrind
      - name: Configure unit tests
        run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DJDWP_UNIT_TEST=1
      - name: Build unit tests
        run: cmake --build build
      - name: Run unit tests with memcheck
        run: ctest --test-dir build --verbose -T memcheck --overwrite MemoryCheckCommand="/usr/bin/valgrind"
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: memcheck-logs-run-${{ github.run_number }}-attempt-${{ github.run_attempt }}-${{ runner.os }}
          path: build/Testing/Temporary/MemoryChecker*.log
          retention-days: 7

  test_e2e:
    name: "E2E Tests"
    runs-on: ubuntu-latest
    needs: build_debug
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
      - name: Install test and runtime dependencies
        run: sudo apt update --quiet && sudo apt install --quiet -y libcmocka-dev
      - name: Configure E2E tests
        run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DJDWP_E2E_TEST=1 -DJDWP_ENABLE_FIXTURES=1
      - name: Build E2E tests
        run: cmake --build build
      - name: Run unit tests with memcheck
        run: ctest --test-dir build --verbose


  build_release:
    name: Build Release
    runs-on: ubuntu-latest
    needs:
      - test_unit
      - test_unit_memcheck
      - test_e2e
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt update --quiet && sudo apt install --quiet -y libcmocka-dev
      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build library
        run: cmake --build build --target jdwp
